//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EOL_tesztelo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DESKTOP-8FO0A37\\EOL_TESTER")]
        public string SQLDataSource {
            get {
                return ((string)(this["SQLDataSource"]));
            }
            set {
                this["SQLDataSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EOL_792")]
        public string SQLInitialCatalog {
            get {
                return ((string)(this["SQLInitialCatalog"]));
            }
            set {
                this["SQLInitialCatalog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sa")]
        public string SQLUserID {
            get {
                return ((string)(this["SQLUserID"]));
            }
            set {
                this["SQLUserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ja61")]
        public string SQLPassword {
            get {
                return ((string)(this["SQLPassword"]));
            }
            set {
                this["SQLPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192")]
        public int PLC_IP_1 {
            get {
                return ((int)(this["PLC_IP_1"]));
            }
            set {
                this["PLC_IP_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("168")]
        public int PLC_IP_2 {
            get {
                return ((int)(this["PLC_IP_2"]));
            }
            set {
                this["PLC_IP_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PLC_IP_3 {
            get {
                return ((int)(this["PLC_IP_3"]));
            }
            set {
                this["PLC_IP_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int PLC_IP_4 {
            get {
                return ((int)(this["PLC_IP_4"]));
            }
            set {
                this["PLC_IP_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PLC_Port {
            get {
                return ((int)(this["PLC_Port"]));
            }
            set {
                this["PLC_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpMeasOpt_M1_Active {
            get {
                return ((bool)(this["OpMeasOpt_M1_Active"]));
            }
            set {
                this["OpMeasOpt_M1_Active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpMeasOpt_M2_Active {
            get {
                return ((bool)(this["OpMeasOpt_M2_Active"]));
            }
            set {
                this["OpMeasOpt_M2_Active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpMeasOpt_M3_Active {
            get {
                return ((bool)(this["OpMeasOpt_M3_Active"]));
            }
            set {
                this["OpMeasOpt_M3_Active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int PC_id {
            get {
                return ((int)(this["PC_id"]));
            }
            set {
                this["PC_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MeasurementCounterNormalOnly {
            get {
                return ((int)(this["MeasurementCounterNormalOnly"]));
            }
            set {
                this["MeasurementCounterNormalOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MeasurementCounterNormal {
            get {
                return ((int)(this["MeasurementCounterNormal"]));
            }
            set {
                this["MeasurementCounterNormal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MeasurementCounterEtalonOnly {
            get {
                return ((int)(this["MeasurementCounterEtalonOnly"]));
            }
            set {
                this["MeasurementCounterEtalonOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MeasurementCounterEtalon {
            get {
                return ((int)(this["MeasurementCounterEtalon"]));
            }
            set {
                this["MeasurementCounterEtalon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MeasurementCounterOilOnly {
            get {
                return ((int)(this["MeasurementCounterOilOnly"]));
            }
            set {
                this["MeasurementCounterOilOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MeasurementCounterOil {
            get {
                return ((int)(this["MeasurementCounterOil"]));
            }
            set {
                this["MeasurementCounterOil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpPrinter {
            get {
                return ((string)(this["OpPrinter"]));
            }
            set {
                this["OpPrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM3")]
        public string EOL_Port {
            get {
                return ((string)(this["EOL_Port"]));
            }
            set {
                this["EOL_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int darabSzamlaloMegfelelo {
            get {
                return ((int)(this["darabSzamlaloMegfelelo"]));
            }
            set {
                this["darabSzamlaloMegfelelo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int darabSzamlaloSelejt {
            get {
                return ((int)(this["darabSzamlaloSelejt"]));
            }
            set {
                this["darabSzamlaloSelejt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveFolderBrowser {
            get {
                return ((string)(this["SaveFolderBrowser"]));
            }
            set {
                this["SaveFolderBrowser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveName {
            get {
                return ((string)(this["SaveName"]));
            }
            set {
                this["SaveName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020.11.30")]
        public string SaveStart {
            get {
                return ((string)(this["SaveStart"]));
            }
            set {
                this["SaveStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020.11.30")]
        public string SaveFinish {
            get {
                return ((string)(this["SaveFinish"]));
            }
            set {
                this["SaveFinish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KIONPartNumber_1 {
            get {
                return ((string)(this["KIONPartNumber_1"]));
            }
            set {
                this["KIONPartNumber_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StabilPartNumber_1 {
            get {
                return ((string)(this["StabilPartNumber_1"]));
            }
            set {
                this["StabilPartNumber_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KIONPartNumber_2 {
            get {
                return ((string)(this["KIONPartNumber_2"]));
            }
            set {
                this["KIONPartNumber_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StabilPartNumber_2 {
            get {
                return ((string)(this["StabilPartNumber_2"]));
            }
            set {
                this["StabilPartNumber_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KIONPartNumber_3 {
            get {
                return ((string)(this["KIONPartNumber_3"]));
            }
            set {
                this["KIONPartNumber_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StabilPartNumber_3 {
            get {
                return ((string)(this["StabilPartNumber_3"]));
            }
            set {
                this["StabilPartNumber_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020-01-01")]
        public global::System.DateTime OpMeasOpt_M1 {
            get {
                return ((global::System.DateTime)(this["OpMeasOpt_M1"]));
            }
            set {
                this["OpMeasOpt_M1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020-01-01")]
        public global::System.DateTime OpMeasOpt_M2 {
            get {
                return ((global::System.DateTime)(this["OpMeasOpt_M2"]));
            }
            set {
                this["OpMeasOpt_M2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020-01-01")]
        public global::System.DateTime OpMeasOpt_M3 {
            get {
                return ((global::System.DateTime)(this["OpMeasOpt_M3"]));
            }
            set {
                this["OpMeasOpt_M3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020-01-01")]
        public global::System.DateTime OpMeasOpt_M_Last {
            get {
                return ((global::System.DateTime)(this["OpMeasOpt_M_Last"]));
            }
            set {
                this["OpMeasOpt_M_Last"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SearchSerialNumber {
            get {
                return ((string)(this["SearchSerialNumber"]));
            }
            set {
                this["SearchSerialNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tipus 1")]
        public string Type1Text {
            get {
                return ((string)(this["Type1Text"]));
            }
            set {
                this["Type1Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tipus 2")]
        public string Type2Text {
            get {
                return ((string)(this["Type2Text"]));
            }
            set {
                this["Type2Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tipus 3")]
        public string Type3Text {
            get {
                return ((string)(this["Type3Text"]));
            }
            set {
                this["Type3Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FirstStartRecalibration {
            get {
                return ((bool)(this["FirstStartRecalibration"]));
            }
            set {
                this["FirstStartRecalibration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TypeIndex {
            get {
                return ((int)(this["TypeIndex"]));
            }
            set {
                this["TypeIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JJJYY")]
        public string CimkeYearDay {
            get {
                return ((string)(this["CimkeYearDay"]));
            }
            set {
                this["CimkeYearDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("STABIL 792900")]
        public string CimkeStabilPartNumber {
            get {
                return ((string)(this["CimkeStabilPartNumber"]));
            }
            set {
                this["CimkeStabilPartNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25.3040.45.0600.0A")]
        public string CimkexyPartNumber {
            get {
                return ((string)(this["CimkexyPartNumber"]));
            }
            set {
                this["CimkexyPartNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("530404506000A")]
        public string CimkeQR_xyPartNumber {
            get {
                return ((string)(this["CimkeQR_xyPartNumber"]));
            }
            set {
                this["CimkeQR_xyPartNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123456789")]
        public string CimkeQR_SerialNumber {
            get {
                return ((string)(this["CimkeQR_SerialNumber"]));
            }
            set {
                this["CimkeQR_SerialNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20210719")]
        public string CimkeQR_YYYYMMDD {
            get {
                return ((string)(this["CimkeQR_YYYYMMDD"]));
            }
            set {
                this["CimkeQR_YYYYMMDD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SerialNumber")]
        public string CimkeHibasSerialNumber {
            get {
                return ((string)(this["CimkeHibasSerialNumber"]));
            }
            set {
                this["CimkeHibasSerialNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Datum")]
        public string CimkeHibasDatum {
            get {
                return ((string)(this["CimkeHibasDatum"]));
            }
            set {
                this["CimkeHibasDatum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hibamegnevezes")]
        public string CimkeHibasHiba {
            get {
                return ((string)(this["CimkeHibasHiba"]));
            }
            set {
                this["CimkeHibasHiba"] = value;
            }
        }
    }
}
